[package]
name = "mining"
version = "0.1.0"
authors = ["ccckmit <ccckmit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.0"
